version: '3'

services:
  nginx:
    build: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static:/etc/nginx/html/static
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - ml_files
      - navidrome
  ml_files:
    restart: unless-stopped
    build: .
    volumes:
      - ./files:/home/app/code/files
  navidrome:
    image: deluan/navidrome:latest
    user: 1003:1003
    restart: unless-stopped
    environment:
      # This is part of my reverse proxy setup; see below.
      ND_BASEURL: "/muz"
      # Re-scan the music library every 15 minutes.
      ND_SCANSCHEDULE: "@every 15m"
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
    volumes:
      - "/opt/navidrome/data:/data"
      - "/home/muz/muz:/music:ro"
